# Assumes that pnpm is set up correctly and that dependencies are installed.
name: Publish Snapshots
description: Publish development snapshots to the npm registry
inputs:
  npm-token:
    description: NPM token for publishing packages
    required: true
  snapshot-tag:
    description: Name of the snapshot build tag (e.g. "dev")
    required: false
    default: "dev"
runs:
  using: "composite"
  steps:
    # Bumps versions in package.json (see https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md)
    # The changes should not be committed to any branch: the "releases" are not part of the version history.
    - name: Version packages
      shell: bash
      run: |
        echo "Publishing snapshot from ${{ github.ref_name}} using tag ${{ inputs.snapshot-tag }}"
        pnpm changeset version --snapshot ${{ inputs.snapshot-tag }}

    # Replaces `workspace:^`` with `workspace:*`
    - name: Rewrite inter-workspace dependencies
      shell: bash
      run: |
        pnpm tsx ./support/prepare-snapshots.ts

    # Note: must happen after versioning because the updated package.json files will be copied into dist/
    - name: Build packages
      shell: bash
      run: pnpm build-packages

    - name: Publish packages
      shell: bash
      run: |
        echo "Published packages" >> publish.log
        echo "==================" >> publish.log
        echo "" >> publish.log

        # Stdout of publish contains the published package names and versions
        pnpm publish -r --access public --tag ${{ inputs.snapshot-tag }} --no-git-checks | tee -a publish.log
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: List packages
      shell: bash
      run: |
        cat publish.log
