packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"
  - .

auditConfig:
  ignoreCves: []

autoInstallPeers: true

catalog:
  "@chakra-ui/cli": ^3.24.2
  "@chakra-ui/react": ^3.24.2
  "@changesets/cli": 2.29.5
  "@conterra/reactivity-core": ^0.7.0
  "@emotion/cache": ^11.14.0
  "@emotion/react": ^11.14.0
  "@formatjs/intl": ^3.1.6
  "@open-pioneer/build-package-cli": ^3.0.3
  "@open-pioneer/build-support": ^3.0.3
  "@open-pioneer/check-pnpm-duplicates": ^0.2.3
  "@open-pioneer/vite-plugin-pioneer": ^5.0.0
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.19.9
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@typescript-eslint/eslint-plugin": ^8.38.0
  "@typescript-eslint/parser": ^8.38.0
  "@vitejs/plugin-react-swc": ^3.11.0
  classnames: ^2.5.1
  eslint: ^8.57.1
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.1.4
  fast-glob: ^3.3.3
  framer-motion: ^12.23.9
  handlebars: ^4.7.8
  happy-dom: ^18.0.1
  husky: ^9.1.7
  js-yaml: ^4.1.0
  keycloak-js: ^26.2.0
  lint-staged: ^16.1.2
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  react-icons: 5.5.0
  react-json-view: ^1.21.3
  react-use: ^17.6.0
  rimraf: ^6.0.1
  sass: ^1.89.2
  tsx: ^4.20.3
  typedoc: ^0.28.7
  typescript: ^5.8.3
  vite: ^7.0.6
  vite-plugin-eslint: ^1.8.1
  vitest: ^3.2.4
  zx: ^8.7.1

dangerouslyAllowAllBuilds: false

dedupePeerDependents: true

ignorePatchFailures: false

ignoreWorkspaceCycles: true

linkWorkspacePackages: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

overrides:
  "@babel/runtime": ">=7.26.10"
  brace-expansion@>=1.0.0 <=1.1.11: ^1.1.12
  brace-expansion@>=2.0.0 <=2.0.1: ^2.0.2
  braces@<3.0.3: ">=3.0.3"
  cross-spawn@<7.0.5: ">=7.0.5"
  esbuild@<0.25.0: ">=0.25.0"
  fast-loops@<1.1.4: ">=1.1.4"
  micromatch@<4.0.8: ">=4.0.8"
  nanoid@<3.3.8: ^3.3.8
  semver@<7.5.2: ">=7.5.2"
  source-map@<0.6.1: ">=0.6.1"
  stylis@<4.3.5: ">= 4.3.5"
  tmp@<=0.2.3: ^0.2.4
  tough-cookie@<4.1.3: ">=4.1.3"
  vite-plugin-eslint>rollup: ">=3.29.5"

patchedDependencies:
  "@ark-ui/react@*": patches/@ark-ui__react.patch

peerDependencyRules:
  allowedVersions:
    flux>react: ">=19"
    react-json-view>react: ">=19"
    react-json-view>react-dom: ">=19"

shamefullyHoist: true

strictPeerDependencies: true
