packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"
  - .

# Shared version expressions (yaml anchors).
# This is a yaml feature and is not interpreted by pnpm directly.
__versions:
  - &react_version ^19.0.0

# https://pnpm.io/catalogs
catalog:
  "@chakra-ui/react": ^3.5.0
  "@chakra-ui/cli": ^3.5.0
  "@conterra/reactivity-core": ^0.4.3
  "@emotion/cache": ^11.14.0
  "@emotion/react": ^11.14.0
  "@formatjs/intl": ^3.1.4
  classnames: ^2.3.2
  framer-motion: ^12.4.7
  keycloak-js: ^26.0.2
  react-dom: *react_version
  react-json-view: ^1.21.3
  react-use: ^17.5.1
  react-icons: ^5.3.0
  react: *react_version

  # Devtools
  "@changesets/cli": 2.27.9
  "@open-pioneer/build-package-cli": ^3.0.0
  "@open-pioneer/build-support": ^3.0.0
  "@open-pioneer/check-pnpm-duplicates": "^0.2.0"
  "@open-pioneer/vite-plugin-pioneer": ^4.0.0
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.2
  "@testing-library/react": ^16.2.0
  "@testing-library/user-event": ^14.5.2
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.14.8
  "@types/react-dom": ^19.0.4
  "@types/react": ^19.0.10
  "@typescript-eslint/eslint-plugin": ^8.11.0
  "@typescript-eslint/parser": ^8.11.0
  "@vitejs/plugin-react-swc": ^3.8.0
  eslint-config-prettier: ^10.0.1
  eslint-import-resolver-typescript: ^3.6.3
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react: ^7.37.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint: ^8.57.1
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^17.1.1
  husky: ^9.1.6
  js-yaml: ^4.1.0
  lint-staged: ^15.2.10
  prettier: ^3.3.3
  rimraf: ^6.0.1
  sass: ^1.85.0
  typedoc: ^0.27.7
  typescript: ^5.7.3
  vite-plugin-eslint: ^1.8.1
  vite: ^6.1.1
  vitest: ^3.0.6
