# Example for an azure-pipelines.yml file to build the project and produce a build artifact.
# Based on pnpm's example at https://pnpm.io/continuous-integration#azure-pipelines
#
# See also the Github Actions Workflows in the `.github` directory of this repository.
trigger:
  - main

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  - checkout: self

  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      corepack enable
      corepack prepare pnpm@latest-7 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: Setup pnpm

  - script: |
      pnpm install
    displayName: Install dependencies

  - script: |
      pnpm lint
      pnpm vitest run
    displayName: Run checks

  - script: |
      pnpm build
      pnpm build-docs
    displayName: Build app

  - publish: dist
    artifact: Build
