# Assumes that pnpm is set up correctly and that dependencies are installed.
name: Deploy demo
description: Deploys demo site to GitHub Pages
inputs:
  src-repo:
    description: "ID of the source repository"
    required: true
  src-dir:
    description: "Source directory to deploy (contains build site)"
    required: false
    default: "site"
  target-path:
    description: "Target sub path (e.g. latest or dev)"
    required: true
  token:
    description: "Deployment token for GitHub Pages"
    required: true
runs:
  using: "composite"
  steps:
    - name: Print configuration
      shell: bash
      run: |
        TARGET_PATH="${{ inputs.src-repo }}/${{ inputs.target-path }}"

        echo "src-dir: ${{ inputs.src-dir }}"
        echo "src-repo: ${{ inputs.src-repo }}"
        echo "target-repository: open-pioneer/trails-demo"
        echo "resolved target path: $TARGET_PATH"

        echo "TARGET_PATH=$TARGET_PATH" >> $GITHUB_ENV

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository-name: open-pioneer/trails-demo
        folder: ${{ inputs.src-dir }}
        target-folder: ${{ env.TARGET_PATH }}
        git-config-name: "github-actions[bot]"
        git-config-email: "41898282+github-actions[bot]@users.noreply.github.com"
        token: ${{ inputs.token }}
