// SPDX-FileCopyrightText: 2023-2025 Open Pioneer project (https://github.com/open-pioneer)
// SPDX-License-Identifier: Apache-2.0
import { defineBuildConfig } from "@open-pioneer/build-support";

export default defineBuildConfig({
    i18n: ["en", "de"],
    entryPoints: [
        "accordion.tsx",
        "action-bar.tsx",
        "alert.tsx",
        "avatar.tsx",
        "blockquote.tsx",
        "breadcrumb.tsx",
        "checkbox.tsx",
        "checkbox-card.tsx",
        "clipboard.tsx",
        "close-button.tsx",
        "color-picker.tsx",
        "data-list.tsx",
        "dialog.tsx",
        "drawer.tsx",
        "empty-state.tsx",
        "field.tsx",
        "file-upload.tsx",
        "hover-card.tsx",
        "input-group.tsx",
        "link-button.tsx",
        "menu.tsx",
        "native-select.tsx",
        "number-input.tsx",
        "pagination.tsx",
        "password-input.tsx",
        "pin-input.tsx",
        "popover.tsx",
        "progress.tsx",
        "progress-circle.tsx",
        "prose.tsx",
        "qr-code.tsx",
        "radio.tsx",
        "radio-card.tsx",
        "rating.tsx",
        "segmented-control.tsx",
        "select.tsx",
        "skeleton.tsx",
        "slider.tsx",
        "stat.tsx",
        "status.tsx",
        "stepper-input.tsx",
        "steps.tsx",
        "switch.tsx",
        "tag.tsx",
        "timeline.tsx",
        "toggle.tsx",
        "toggle-tip.tsx",
        "tooltip.tsx"
    ],
    publishConfig: {
        strict: true
    }
});
