# Assumes that pnpm is set up correctly and that dependencies are installed.
name: Deploy PR Preview
description: Deploys a preview of a pull request to GitHub Pages
inputs:
  src-repo:
    description: "ID of the source repository"
    required: true
  token:
    description: "Deployment token for GitHub Pages"
    required: true

runs:
  using: "composite"
  steps:
      - name: Print configuration
        shell: bash
        run: |
          echo "src-repo: ${{ inputs.src-repo }}"
          echo "target-repository: open-pioneer/trails-pr-previews"
      - name: Configure Git User
        run: |
          git config --global user.name "Open Pioneer Automation"
          git config --global user.email "contact@openpioneer.dev"
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/www/
          umbrella-dir: "${{ inputs.src-repo }}/pr-previews"
          deploy-repository: open-pioneer/trails-pr-previews
          token: ${{ inputs.token }}
